### ISSUE TITLE
[BUG]  LifeCycleManager throw cala.collection.immutable.HashMap$HashTrieMap cannot be cast to java.util.HashMap when handle destroyBuffersWithRetry

### ISSUE THREAD

**Issue by AngersZhuuuu** [alibaba/RemoteShuffleService#171]
### What is the bug?
```
22/06/27 16:37:53 ERROR Inbox: Ignoring error
java.lang.ClassCastException: scala.collection.immutable.HashMap$HashTrieMap cannot be cast to java.util.HashMap
	at com.aliyun.emr.rss.client.write.LifecycleManager.reserveSlotsWithRetry(LifecycleManager.scala:948)
	at com.aliyun.emr.rss.client.write.LifecycleManager.handleRegisterShuffle(LifecycleManager.scala:302)
	at com.aliyun.emr.rss.client.write.LifecycleManager$$anonfun$receiveAndReply$1.applyOrElse(LifecycleManager.scala:188)
	at com.aliyun.emr.rss.common.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:110)
	at com.aliyun.emr.rss.common.rpc.netty.Inbox.safelyCall(Inbox.scala:214)
	at com.aliyun.emr.rss.common.rpc.netty.Inbox.process(Inbox.scala:107)
	at com.aliyun.emr.rss.common.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### How to reproduce the bug?
Steps to reproduce the bug.

### Could you share logs or screenshots?
If applicable, add logs/screenshots to help explain your problem.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment]
Fixed and merged.
