### ISSUE TITLE
[QUESTION] Spark job exec failed

### ISSUE THREAD

**Issue by CCweixiao** [alibaba/RemoteShuffleService#23]
软件版本：
spark2.4.5 
hadoop2.6.0-cdh5.13.1 

spark作业提交核心配置参数：

$SPARK_HOME/bin/spark-submit  \
--master yarn   \
--queue low.bigdata_online \
--executor-memory 10G \
--executor-cores 4 \
--driver-memory 5g  \
--conf spark.ui.port=$port \
--conf spark.executor.memoryOverhead=4g \
--conf spark.dynamicAllocation.minExecutors=1 \
--conf spark.dynamicAllocation.maxExecutors=24 \
--conf spark.yarn.maxAppAttempts=1 \
--conf spark.speculation=true \
--conf spark.dynamicAllocation.enabled=true \
--conf spark.shuffle.service.enabled=false \
--conf spark.shuffle.manager=org.apache.spark.shuffle.rss.RssShuffleManager \
--conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
--conf spark.rss.master.address=master-ip:9097 \
--conf spark.rss.shuffle.writer.mode=hash \
--conf spark.rss.push.data.replicate=true \
--conf spark.yarn.archive=hdfs:///data/spark2.4.5_rss_jars \
......

问题描述：
RSS 服务运行正常，Spark作业运行时抛如下异常，（Spark Jars目录下是存在rss-shuffle-manager-1.0.0-shaded.jar的）

: java.lang.NoClassDefFoundError: com/aliyun/emr/rss/client/write/LifecycleManager
	at org.apache.spark.shuffle.rss.RssShuffleManager.org$apache$spark$shuffle$rss$RssShuffleManager$$initializeLifecycleManager(RssShuffleManager.scala:60)
	at org.apache.spark.shuffle.rss.RssShuffleManager$$anonfun$registerShuffle$2.apply(RssShuffleManager.scala:76)
	at org.apache.spark.shuffle.rss.RssShuffleManager$$anonfun$registerShuffle$2.apply(RssShuffleManager.scala:76)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.shuffle.rss.RssShuffleManager.registerShuffle(RssShuffleManager.scala:76)
	at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:93)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$.prepareShuffleDependency(ShuffleExchangeExec.scala:323)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.prepareShuffleDependency(ShuffleExchangeExec.scala:91)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$doExecute$1.apply(ShuffleExchangeExec.scala:128)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$doExecute$1.apply(ShuffleExchangeExec.scala:119)
	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
	at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.doExecute(ShuffleExchangeExec.scala:119)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:391)
	at org.apache.spark.sql.execution.aggregate.HashAggregateExec.inputRDDs(HashAggregateExec.scala:151)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:627)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:296)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2836)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2835)
	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2835)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.aliyun.emr.rss.client.write.LifecycleManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 48 more

**Comment by FMX** [comment]
消息收到。。。

**Comment by CCweixiao** [comment]
--jars 引入 或者把rss jar放到Spark的jars目录下，都不行，一直报上述异常

**Comment by wangshengjie123** [comment]
> --jars 引入 或者把rss jar放到Spark的jars目录下，都不行，一直报上述异常

We have fixed this issue a moment ago, could you git pull the new code and rebuild? Thanks for report this issue.

**Comment by CCweixiao** [comment]
> > --jars 引入 或者把rss jar放到Spark的jars目录下，都不行，一直报上述异常
> 
> We have fixed this issue a moment ago, could you git pull the new code and rebuild? Thanks for report this issue, @CCweixiao.

是打包的问题，已经跑通了，感谢
