### ISSUE TITLE
[QUESTION] How to enable dynamic executors allocation by using RSS to manage shuffle

### ISSUE THREAD

**Issue by JinyLeeChina** [alibaba/RemoteShuffleService#319]
22/08/11 17:08:04 WARN cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
22/08/11 17:08:05 ERROR yarn.ApplicationMaster: User class threw exception: org.apache.spark.SparkException: Dynamic allocation of executors requires the external shuffle service. You may enable this through spark.shuffle.service.enabled.
org.apache.spark.SparkException: Dynamic allocation of executors requires the external shuffle service. You may enable this through spark.shuffle.service.enabled.
	at org.apache.spark.ExecutorAllocationManager.validateSettings(ExecutorAllocationManager.scala:234)
	at org.apache.spark.ExecutorAllocationManager.<init>(ExecutorAllocationManager.scala:143)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:546)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2549)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:944)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)

**Comment by JinyLeeChina** [comment]
@FMX Can it support enable dynamic executors allocation

**Comment by AngersZhuuuu** [comment]
> @FMX Can it support enable dynamic executors allocation

After backport patch https://github.com/alibaba/RemoteShuffleService/tree/main/assets/spark-patch  you can enable dynamic allocation

**Comment by JinyLeeChina** [comment]
Is this PR code included in version 0.1.1-release ？

**Comment by AngersZhuuuu** [comment]
> Is this PR code included in version 0.1.1-release ？

you should backport the patch to your spark's code

**Comment by JinyLeeChina** [comment]
OK. I got it, thanks

**Comment by AngersZhuuuu** [comment]
Can close this.
