### ISSUE TITLE
[BUG] On Kubernetes RSS Master Start Fail

### ISSUE THREAD

**Issue by zwangsheng** [alibaba/RemoteShuffleService#379]
### What is the bug?
Follow On_Kubernetes.md to start RSS on Kubernetes.
Fail to Start RSS Master.

### How to reproduce the bug?
Steps to reproduce the bug.

### Could you share logs or screenshots?
```
starting com.aliyun.emr.rss.service.deploy.master.Master, logging to /opt/rss-0.2.0-SNAPSHOT-bin-release/logs/rss--com.aliyun.emr.rss.service.deploy.master.Master-1-shuffleservice-master-0.out
Exception in thread "main" java.lang.NumberFormatException: For input string: "tcp://XXXXX:7337"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
	at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
	at com.aliyun.emr.rss.service.deploy.master.MasterArguments.<init>(MasterArguments.scala:35)
	at com.aliyun.emr.rss.service.deploy.master.Master$.main(Master.scala:650)
	at com.aliyun.emr.rss.service.deploy.master.Master.main(Master.scala)
```

/cc @fanyilun 

/assign @who-can-solve-this-bug

**Comment by zwangsheng** [comment]
We can circumvent this problem by setting `RSS_MASTER_PORT: 7337` in `${RSS_HOME}/docker/helm/values.yaml`.

**Comment by zwangsheng** [comment]
Personal circumstances cause this that do not recur after removing factors. Close this issuse.
