### ISSUE TITLE
[BUG] SortBasedPusher pass 0 to allocateArray when calling growPointerArrayIfNecessary

### ISSUE THREAD

**Issue by nafiyAix** [alibaba/RemoteShuffleService#691]
### What is the bug(with logs or screenshots)?
java.lang.AssertionError: assertion failed: invalid number of bytes requested: 0
	at scala.Predef$.assert(Predef.scala:223)
	at org.apache.spark.memory.ExecutionMemoryPool.acquireMemory(ExecutionMemoryPool.scala:96)
	at org.apache.spark.memory.UnifiedMemoryManager.acquireExecutionMemory(UnifiedMemoryManager.scala:148)
	at org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:147)
	at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:289)
	at org.apache.spark.memory.MemoryConsumer.allocateArray(MemoryConsumer.java:95)
	at org.apache.spark.shuffle.rss.SortBasedPusher.growPointerArrayIfNecessary(SortBasedPusher.java:227)
	at org.apache.spark.shuffle.rss.SortBasedPusher.insertRecord(SortBasedPusher.java:190)
	at org.apache.spark.shuffle.rss.SortBasedShuffleWriter.fastWrite0(SortBasedShuffleWriter.java:200)
	at org.apache.spark.shuffle.rss.SortBasedShuffleWriter.write(SortBasedShuffleWriter.java:156)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1465)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### How to reproduce the bug?
Steps to reproduce the bug.

/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by nafiyAix** [comment]
ping @AngersZhuuuu
